FROM ubuntu:22.04

# Install ansible and dependencies
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
  apt-get install -y \
  ansible \
  openssh-client \
  git \
  make \
  && rm -rf /var/lib/apt/lists/*

# Pre-install common ansible collections
RUN ansible-galaxy collection install community.docker

# Set working directory
WORKDIR /workspace

# Default command
CMD ["/bin/bash"]
