services:
  registry:
    image: registry:3.1.1@sha256:85347ed2ecde64161c7a4788a4d7d3dcc9d6f86f7be95834022e3c6a423a945a
    container_name: registry
    restart: unless-stopped
    environment:
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_HTTP_TLS_CERTFILE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEYFILE=/certs/domain.key
    volumes:
      - ./registry/certs:/certs
      - registry-data:/var/lib/registry
    networks:
      - reverse-proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.rule=Host(`registry.oscarcorner.com`)"
      - "traefik.http.routers.registry.service=registry-service"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.tls.certresolver=route53"
      - "traefik.http.routers.registry.tls.domains[0].main=oscarcorner.com"
      - "traefik.http.routers.registry.tls.domains[0].sans=*.oscarcorner.com"
      - "traefik.http.services.registry-service.loadbalancer.server.port=5000"

volumes:
  registry-data:

networks:
  reverse-proxy-network:
    external: true

