services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine@sha256:cb3339abbd6e18942cd8ac3349f0c371a82ba5b6204b242563ba299e7956cbd0
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    volumes:
      - ./valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest@sha256:174f6a8498d88d2d98c265a952c2d552859bf315cd505746d1c0d4fbec37952f
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    ports:
      - "127.0.0.1:8080:8080"
    labels:
      traefik.enable: true
      traefik.http.routers.search.entrypoints: websecure
      traefik.http.routers.search.rule: Host(`search.oscarcorner.com`)
      traefik.http.services.search.loadbalancer.server.port: 8080
      traefik.http.routers.search.tls.certresolver: route53
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-search.oscarcorner.com}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  valkey-data2:
  searxng-data:
networks:
  reverse-proxy-network:
    external: true
