services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest@sha256:5286edb35782454ab8a102c5eff6b54bff745853191b46aeead95f225aa6dfb6
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - reverse-proxy-network
    volumes:
      - ./searxng.yaml:/etc/searxng/settings.yml:ro
      - searxng-cache:/var/cache/searxng
    environment:
      SEARXNG_BASE_URL: https://search.oscarcorner.com/
      SEARXNG_VALKEY_URL: valkey://valkey:6379/0
    labels:
      traefik.enable: true
      traefik.http.routers.searxng.entrypoints: websecure
      traefik.http.routers.searxng.rule: Host(`search.oscarcorner.com`)
      traefik.http.services.searxng.loadbalancer.server.port: 8080
      traefik.http.routers.searxng.tls.certresolver: route53

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data:/data/
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    external: true

volumes:
  valkey-data:
  searxng-cache:
