use_default_settings: true

server:
  base_url: https://search.oscarcorner.com/
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false

search:
  safe_search: 0
  formats:
    - html
    - json

valkey:
  url: valkey://valkey:6379/0

outgoing:
  request_timeout: 5.0

engines:
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: wikipedia
    disabled: false
