server:
  base_url: https://search.oscarcorner.com/
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false

search:
  safe_search: 0
  formats:
    - html
    - json

valkey:
  url: valkey://valkey:6379/0

outgoing:
  request_timeout: 5.0

engines:
  - name: google
    engine: google
    shortcut: go
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    categories: [general]
