server:
  base_url: https://searxng.oscarcorner.com/
  bind_address: "0.0.0.0"
  bind_port: 8080
  listen_timeout: 120000

search:
  safe_search: 0
  safe_search_enabled: true
  formats:
    - html
    - json
engines:
  - name: google
    engine: google
  - name: duckduckgo
    engine: duckduckgo
  - name: wikipedia
    engine: wikipedia

valkey:
  url: redis://redis:6379/0
