#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
#
- name: Find local docker service directories
  delegate_to: localhost
  run_once: true
  find:
    paths: "{{ docker_compose_path }}"
    recurse: no
    file_type: directory
  register: local_docker_compose

- name: Create docker service directories on remote
  become: yes
  file:
    path: "{{ item.path | basename }}"
    state: directory
    owner: "{{ docker_volume_owner }}"
    group: "{{ docker_volume_group }}"
  loop: "{{ local_docker_compose.files }}"
- name: Copy all docker files and folders to remote
  become: yes
  copy:
    src: "{{ item.path }}/"
    dest: "{{ item.path | basename }}/"
    mode: preserve
    owner: "{{ docker_volume_owner }}"
    group: "{{ docker_volume_group }}"
    directory_mode: "0755"
  loop: "{{ local_docker_compose.files }}"

- name: Ensure docker volumes have correct permissions with GID 1000
  become: yes
  file:
    path: "{{ item.path | basename }}"
    owner: "{{ docker_volume_owner }}"
    group: "{{ docker_volume_gid }}"
    mode: "0755"
    recurse: yes
  loop: "{{ local_docker_compose.files }}"

- name: Set docker-compose files to 600 permissions
  become: yes
  file:
    path: "{{ item.path | basename }}/docker-compose.yaml"
    owner: "{{ docker_volume_owner }}"
    group: "{{ docker_volume_group }}"
    mode: "0600"
  loop: "{{ local_docker_compose.files }}"
  ignore_errors: yes

- name: Find shell scripts in docker directories
  become: yes
  find:
    paths: "{{ item.path | basename }}"
    patterns: "*.sh"
    recurse: true
  loop: "{{ local_docker_compose.files }}"
  register: shell_scripts
  ignore_errors: true

- name: Ensure shell scripts are executable
  become: yes
  file:
    path: "{{ item.path }}"
    mode: "0755"
    owner: "ci"
    group: "ci"
  loop: "{{ shell_scripts.results | selectattr('files', 'defined') | map(attribute='files') | flatten }}"
  when: shell_scripts.results is defined
- name: Run docker compose up
  become: yes
  become_user: "{{ docker_volume_owner }}"
  community.docker.docker_compose_v2:
    project_src: "{{ item.path | basename }}"
    remove_orphans: true
    remove_volumes: true
  loop: "{{ local_docker_compose.files }}"
  register: output
- name: show results
  ansible.builtin.debug:
    var: output

- name: Print
  ansible.builtin.debug:
    msg: path "{{ item.path | basename }}/docker-compose.yaml, {{ item.path }}"
  loop: "{{ local_docker_compose.files }}"
