when:
  - event: manual
  - event: push
    branch: main
steps:
  - name: deploy
    image: woodpeckerci/plugin-ansible
    settings:
      playbook: ansible/docker.yaml
      inventory: ansible/hosts
      galaxy: ansible/requirements.yml
      private_key:
        from_secret: deploy_key
