services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    labels:
      traefik.enable: true
      traefik.http.routers.rss.entrypoints: websecure
      traefik.http.routers.rss.rule: Host(`rss.oscarcorner.com`)
      traefik.http.services.rss.loadbalancer.server.port: 80
      traefik.http.routers.rss.tls.certresolver: route53
    environment:
      TZ: Europe/London
      SERVER_DN: "rss.oscarcorner.com"
      PUID: 1000
      PGID: 1000
      CRON_MIN: "13,43"
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    healthcheck:
      test: ["CMD", "cli/health.php"]
      interval: 75s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  reverse-proxy-network:
    external: true
